loki:
  enabled: true
  persistence:
    enabled: false
  config:
    table_manager:
      retention_deletes_enabled: true
    schema_config:
      configs:
        - from: 2020-10-15
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
promtail:
  enabled: true
  extraScrapeConfigs: |
    - job_name: garden-app-logs
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: garden
