grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
nodeExporter:
  enabled: false