mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.91.0"

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

    prometheus:
      config:
        scrape_configs:
          - job_name: 'garden-app'
            scrape_interval: 15s
            static_configs:
              - targets: ['garden-service.garden.svc.cluster.local:80']
            metrics_path: '/metrics'

  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024

    resource:
      attributes:
        - key: service.name
          value: garden-app
          action: upsert

  exporters:
    prometheusremotewrite:
      endpoint: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"

    loki:
      endpoint: "http://loki-gateway.monitoring.svc.cluster.local:80/loki/api/v1/push"

    otlp:
      endpoint: "http://tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true

  service:
    pipelines:
      metrics:
        receivers: [otlp, prometheus]
        processors: [resource, batch]
        exporters: [prometheusremotewrite]

      logs:
        receivers: [otlp]
        processors: [resource, batch]
        exporters: [loki]

      traces:
        receivers: [otlp]
        processors: [resource, batch]
        exporters: [otlp]

# Service configuration - let the chart use its defaults
service:
  type: ClusterIP