apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-deployment
  namespace: garden
  labels:
    app: garden
spec:
  replicas: 2
  selector:
    matchLabels:
      app: garden
  template:
    metadata:
      labels:
        app: garden
    spec:
      containers:
        - name: garden
          image: garden-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
            initialDelaySeconds: 120   # war 60, jetzt 120s
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
            initialDelaySeconds: 60    # war 30, jetzt 60s
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: garden-config
                  key: APP_PORT
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgresql-garden:5432/gardendb"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: garden-postgres-secret
                  key: username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: garden-postgres-secret
                  key: password
            - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
              value: "update"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "garden-app"
          volumeMounts:
            - name: app-storage
              mountPath: /app/data
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: garden-pvc
