architecture: "replicaset"

auth:
  enabled: true
  rootUsername: admin
  rootPassword: s3cr3tPassw0rd
  database: gardendb
  usernames:
    - admin
  passwords:
    - s3cr3tPassw0rd
  databases:
    - gardendb

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""
